### ISSUE TITLE
Authorization request signatures

### ISSUE THREAD

**Issue by bakerdb** [smart-on-fhir/smart-on-fhir.github.io#29]
Ref:  OIDC (16.7)
Risk Assessment Row:  40

Description:  As a countermeasure for request repudiation, the OpenID Connect spec recommends having the client digitally sign requests using a key that supports non-repudiation, with the AS validating the signature. 

Recommendation:  Considering adding request non-repudiation to the profile.

**Comment by jmandel** [comment]
Just as an anchor point, this functionality is optional in the OpenID Spec, and I haven't seen it implemented among the major consumer-facing OIDC deployments. For example:

Google:
https://accounts.google.com/.well-known/openid-configuration

Microsoft:
https://login.windows.net/common/.well-known/openid-configuration

--> both lack the "request_parameter_supported" parameter, indicating they do not support "request objects" at all (let alone signed request objects).

(MITREid does support signed request objects, so it's no big deal to demonstrate this in our reference implementation -- but I'm wary of adding in functionality to our spec that we don't strictly need and which hasn't seen widespread adoption in the consumer world.)

**Comment by bakerdb** [comment]
This would only be applicable for confidential clients.  But I do think it's important -- even more so for use case 5, when requests will cross organizational boundaries, and the organization holding the FHIR resource will need to document the disclosure in a way that will hold up in court.  I know everyone hates optionality, but I think we would remiss if we didn't acknowledge the possibility and value of having the client sign requests.

**Comment by jmandel** [comment]
I'd imagine this wouldn't apply at all to our [security use case 5](https://docs.google.com/document/d/1dFe79QvQryWMkCctL-Kzv0bxhOq-mNPfOjN5rd0JALQ/edit?usp=drive_web), because that use case involves the client generating its own assertion that it can trade for a token. In that use case, the client would never call the authz server's `/authorize` endpoint; it would just call the `/token` endpoint directly. And so the `request` parameter to the authorize endpoint wouldnt' come into play.

(In use case 5, non-repudiation comes from the fact that the client is generating its own signed assertion -- the client's signature over that assertion is what provides non-repudiation.)
