### ISSUE TITLE
Steps for using an ID Token is insufficient

### ISSUE THREAD

**Issue by whitehatguy** [smart-on-fhir/smart-on-fhir.github.io#62]
If the OpenID Connect protocol is legitimately being used for authentication, the steps currently listed for validating an ID token should instead refer individuals to section 3.1.3.7 of the OpenID specification for validation steps.  There are certain key elements, such as validating the audience that are necessary.

In addition, step 6 of section 3.1.3.7 states:

"If the ID Token is received via direct communication between the Client and the Token Endpoint (which it is in this flow), the TLS server validation MAY be used to validate the issuer in place of checking the token signature."

Should we make this explicit in this profile to reduce the overhead of having to support the .well_known endpoint along with hosting signature keys?  There's little additional security afforded here, unless consumers want to somehow utilize such id_tokens within their own internal security implementation.

Finally, the use of OpenID Connect seems to transitively place requirements on the authorization server to support the following parameters in the authentication request.  This should likely be explicitly stated in the documentation:
- nonce
- prompt (minimally, support for prompt=none and response error codes indicating if the user was not previously authenticated.)
- max-age

Other optional functionality would also need to be indicated that it is not supported per the OpenID Connect Discovery specification.  An example is "Passing a Request Object by Value" as described by section 6.1 in the Connect Core spec.

Is the intent here to have EMRs act as full-blown authentication servers (and/or as proxies to the authentication system that they use internally)?  It would seem that passing the FHIR endpoint for the user could be easily achieved as an additional claim.  I haven't seen any Argonaut use case that calls out utilizing the authorization server solely as an authentication system.

**Comment by jmandel** [comment]
HI Matt,

Thanks for these comments!

High-level picture: our intention in using OIDC certainly is to provide
end-user authentication to client apps. I often refer to this by saying
that SMART needs to offer "single-sign-on" capabilities. The core Argonaut
use cases include standalone clinician- and consumer-facing apps, where the
end-user can sign in using her existing EHR-provided identity (e.g. a
portal account). And we do want to support apps that will use id_tokens
"within their own internal security implementation" if I take your meaning
correctly. So yes: I see value in providing signatures over the id_token,
since the software component using the id_token may not always be the same
component that talked to the AS to obtain it.

Absolutely we could try to do all this without OIDC (e.g. by just adding a
"fhir_endpoint_of_currently_signed_in_user" property to our access token
response). But then we need to take care to (re)-specify many of the
details that OIDC has already carefully thought through (e.g. various ways
to get this wrong are described at http://oauth.net/articles/authentication/
).

Getting down to details, then: I agree with your initial position that we
want to specify more, not less. I agree that we (transitively, implicitly)
require servers to support nonce, prompt, and max_age, and this requirement
should be made explicit. When it comes to  "Passing a Request Object by
Value", I think we can let servers decide whether or not to support this
(and indeed, they should document their decision via their discovery
endpoint); it's a nice-to-have in some cases, but not essential to
Argonaut's use cases. And yes, clients should verify `aud` claims. Would
you be willing to submit these fixex as a PR against the Argonaut branch?

Thanks!

  -Josh

**Comment by whitehatguy** [comment]
Josh,

Thanks for the clarification.  Up until this point, I had assumed the inclusion (of OIDC) was only for a standards-based approach to conveying certain attribute claims, such as the URL of the user's FHIR endpoint.  Are the authentication use cases to be considered in a future set of use cases for the Argonaut security group?  The majority of our client organizations utilizing our patient portal solutions already rely on other authentication protocols (i.e. SAML) and single log-out is always a significant concern -- it probably warrants some discussion as to how we envision this ecosystem functioning where the EHR is a relying party/service provider of an existing identity system.

**Comment by jmandel** [comment]
I think it would be a good topic for discussion in Argonaut, certainly! (I
don't think these are explicitly on the agenda today.) I'm definitely
interested in hearing your thoughts around sign-out (so far we've gotten by
simply saying that apps manage sign-out independent of the EHR -- except of
course if an app requests an "online_access" scope, in which case their
refresh tokens will stop working when the user is no longer signed in to
the EHR.)

  -J
