### ISSUE TITLE
When/why is a "launch" scope needed?

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/smart-on-fhir.github.io#74]
>   Are there situations where the scope "launch" would be denied and the workflow would be expected to continue uninterrupted?  We've found a lot of people forget the "launch" scope when making the request, which leads to confusion, as they get a token back without any of their launch information.  It seems like simply having the extension should be sufficient.

In-context at: http://fhir-docs.smarthealthit.org/argonaut-dev/specification/#q-issue-74

**Comment by kpshek** [comment]
To me, this boils down to whether the launch scope is intended to (as the name strongly implies), determine whether the SMART app _can_ launch OR if the launch scope is intended to share patient, encounter, and location context once the SMART app has been authorized to launch.

If the launch scope is just to communicate context, then I can see value in a SMART app that operates cross-patient or perhaps doesn't need a patient at all and simply wants to be able to launch in a vendor agnostic manner using SSO. In this case, the SMART app wouldn't request the launch scope. If this is the intention of the launch scope, then perhaps the name is misleading and a name like _context_ would be more appropriate.

Based on the current documentation ("Permission to obtain launch context when app is launched from an EHR"), it sounds like the launch scope is just to communicate context rather than whether the SMART app can be launched.

**Comment by jmandel** [comment]
@kpshek has it right: this scope was designed to mean "can the EHR share the launch context with the app". Of course there are some cases where, if the answer was "no", then the whole launch kind of fizzles out: namely, any time the app is asking for a `patient/` scope -- because without the `launch` scope, the app would have access to just one patient record but wouldn't know *which* patient record it was. But there can be some sense in asking for `user/` scopes while omitting `launch`.

If we did eliminate this scope, it would have to be with a default behavior expectation of "always provide the launch context". Especially in light of @whitehatguy's proposed "contextless" launch mechanism, I think there *is* value in keeping this explicit.

As to what it's called... I could be swayed here, but my thought  process was: I found "launch" more evocative than "context", and I found "launch_context" verbose.

**Comment by whitehatguy** [comment]
Okay, in keeping the scope as an explicit requirement, which is the desired behavior when a _launch_ parameter is included without including the _launch_ scope?:

- An error is immediately returned to the client application.
- The request is fulfilled.  The access token response does not contain the launch information, and the list of authorized scopes omits the launch scope.
- The request is fulfilled.  The access token response does not contain the launch information, and the list of authorized scopes retains the launch scope.

**Comment by bakerdb** [comment]
I would opt for #1 -- error, with an explanation.  

#2 is likely to produce confusion and possibly a useless token.  
#3 would enable the app to query for the launch information, so would be my 2nd choice.

**Comment by jmandel** [comment]
Now reviewing after some time has passed...

Breaking down by case:

1. **EHR Launch flow.** The real question is, do we care about permitting an app *not to obtain* launch context when it's being launched through the EHR launch flow. I'm willing to say this isn't really that useful. In which case, the value of a `launch` scope disappears.

2. **Standarlone Launch flow.** Here, the app needs to be explicit with scopes like `launch/patient` or `launch/encounter` so the EHR knows what context to gather. But no need for a bare `launch` scope.

3. **Contextless Launch flow.** Obviously it makes no sense to talk about any kind of `launch` scope here; that's the very thing that distinguishes the contextless flow from the standalone flow.

**Comment by whitehatguy** [comment]
I was originally only referring to the fact that a client application sends the "launch" parameter to the EHR, but is required to send both the parameter AND include the scope of "launch".  I wasn't sure what the reason for including the plain "launch" scope was in this situation given the extension is explicitly asking for the launch data already.

**Comment by jmandel** [comment]
Indeed -- and I think I'm agreeing with your original point :-)
